### ISSUE TITLE
write faqs

### ISSUE THREAD

**Issue by jtimon** [freicoin/freico.in#3]
Reestructure the faqs, remove what isn't relevant and add more questions.
Think about how to reuse from https://en.bitcoin.it/wiki/FAQ
A simple link?
Rewrite some answers?

**Comment by maaku** [comment]
No longer applies.

**Comment by jtimon** [comment]
Aren't we going to eventually have a faq section?

**Comment by maaku** [comment]
What happened was that the content of the FAQ section was completely absorbed into the About page, which is what this ticket was about. We certainly could have a FAQ section, although we'd need some questions and answers to put in it.

**Comment by jtimon** [comment]
I see. I've started a brainstorming thread on the forum:

http://www.freicoin.org/freicoin-faqs-t75.html

Not sure if we should reopen this issue or start a new one, whatever you think is more appropriate.
